### PR TITLE
Move optimized ucs22str function to 64bit only

### LINKED ISSUE #39: Recent changes to tds.go mean compilation on GOARCH=386 is no longer possible
**Describe the bug**
Recent changes to tds.go mean compilation on `GOARCH=386` is no longer possible.  As far as I can tell, it is only this file currently preventing support for 386.

**To Reproduce**
````
set GOARCH=386
go build any_go-mssql_based_prog.go
````

**Expected behavior**
Compilation should be able to succeed, regardless of `GOARCH`

### Further technical details
[Line 489](https://github.com/microsoft/go-mssqldb/blob/c33ed631655f2055a27eb1d2a74f14eae81ad946/tds.go#L489) (as of v0.15) reads...
````
nlen8 := len(s) & 0xFFFFFFF8
````
The `len(s)` infers `int`, which is 32 bits on x86 platforms, but `0xFFFFFFF8` does not coerce to a 32-bit int.  I *can* change this to `var nlen8 int64 = int64(len(s)) & 0xFFFFFFF8` and add some extra casts further down to resolve simple comparison mismatches, and it *will* compile, but there is some `unsafe.Pointer` math going on in/around this variable, which I don't immediately understand, and I am not confident it won't lead to a problem further down the line if I PR based on this simplistic fix.

**Additional context**
In the meantime, I have had to vendor the module, and cherry-pick `func ucs22str` from the previous version.  If the pointer math is not trivial to resolve in x86, perhaps the sanest approach is to move this function out of *tds.go* into its own code files *ucs22str.go* and *ucs22str_386.go* and use `+build` tags to conditionally compile both versions -- I *could* PR that if it suits?

### PR DESCRIPTION
**Pull request by shueybubbles**
Fixes #39 
I also moved some test code to 64bit-only as it either doesn't compile for 32bit or fails during the test run. We aren't going to spend much time debugging such failures since they are longstanding at this point. I added a 32bit test run to the appveyor build to help prevent future 32bit breaks.

### CODE REVIEW

**Review by apoorvdeshmukh — COMMENTED** [review]
Is there any workaround for appveyor test failures?
If the -race option is not supported, should we disable this mode?

**Comment by shueybubbles** [comment]
the -race parameter needs to become part of the matrix in the yml

---
In reply to: [1057622190](https://github.com/microsoft/go-mssqldb/pull/43#issuecomment-1057622190) [](http://example.com/codeflow?ancestors=1057622190,1057622190)

**Review by apoorvdeshmukh — APPROVED** [review]

**Comment by ondrejsika** [comment]
Why?

**Comment by shueybubbles** [comment]
> Why?

Because the original PR author who wrote the optimized function didn't build or test it for 32bit and it was just our quickest option to unblock 32bit consumers. I'm open to someone revisiting the optimized function to make it 32bit compatible.

**Pull request merged**
