### PR TITLE
go mod vendor npipe to this repo

### LINKED ISSUE #117: Move npipe implementation into this repo
The `gopkg.in/natefinch/npipe.v2` project is dormant and we need a fix (https://github.com/natefinch/npipe/pull/35).
Rather than fork it into the Microsoft organization I will `go mod vendor` it into the `internal` folder here and modify our copy to have the new API.

### PR DESCRIPTION
**Pull request by shueybubbles**
Fixes #117 
2 parts to the fix
1. Bring the code over and verify it builds
2. Implement `DialExisting` to fix issue where dialing using `np` doesn't quit immediately when the named pipe doesn't exist.

### CODE REVIEW

**Comment by shueybubbles** [comment]
I couldn't get this to work with a `vendor` folder whose only content was this package, nor did it work with a `replace` directive in `go.mod`. I think there's something funky with this old repo that breaks `go build` with new tools.

**Review by apoorvdeshmukh — APPROVED** [review]
:shipit:

**Comment by apoorvdeshmukh** [comment]
Do we need to create another issue to vendor this properly at some later point?

**Comment by shueybubbles** [comment]
since we keep the license and attribution intact we are ok as-is.
thx

**Pull request merged**
