### PR TITLE
Add support for federated authentication with provided access token when prelogin doesnt return preloginFEDAUTHREQUIRED

### LINKED ISSUE #84: prelogin fields data structure breaks when using access token for federated auth with AWS RDS Proxy MS SQL support
**Describe the bug**
1. When i use connection string:

`odbc:server=%s;password={%s};port=%d;fedauth=ActiveDirectoryServicePrincipalAccessToken;`
A valid token as passed as the password, and an AWS RDS MS SQL Proxy configured as the server, I get this error:

`2023/01/29 12:16:08 Error preparing SQL statement:federated authentication is not supported by the server`

2. Below extract from the TDS spec v33 found [here](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/b46a581a-39de-4745-b076-ec4dbb7d13ec):
CleanShot 2023-01-30 at 11 59 58@2x
Says that If the server received preloginFEDAUTHREQUIRED - it MUST respond as above.

3. In the prelogin response, as there is no valid preloginFEDAUTHREQUIRED index (6) the check here passes through to the else statement. (see below for debugger screenshots)

```
else if fe.FedAuthLibrary != FedAuthLibraryReserved {
			return 0, fmt.Errorf("federated authentication is not supported by the server")

```

I worked around this issue by removing the else. I am not sure if this is a problem with this library, or if its an issue with the AWS implementation of the protocol. (see below for example dotnet program which works fine - maybe the dotnet implementation doesn't have a similar check?)

[See diffs for fix](https://github.com/microsoft/go-mssqldb/compare/main...mattgillard:go-mssqldb:main):

Exception message: `2023/01/29 12:16:08 Error preparing SQL statement:federated authentication is not supported by the server`

**To Reproduce**
Include a complete code listing that we can run to reproduce the issue.
See here [for gist](https://gist.github.com/mattgillard/ff124f67c7e16318684c961441fd5aa5)

Instructions as per comment in gist:

1. Create an RDS MS SQL Server (Express is fine for cheapness)
2. Create an RDS Proxy (plug in your requirements)
```
aws rds create-db-proxy \
    --db-proxy-name sqlproxy \
    --engine-family SQLSERVER  \
    --auth Description="MS SQL RDS Proxy",AuthScheme="SECRETS",SecretArn="arn:aws:secretsmanager:ap-southeast-2:1234567890:secret:rdsad5de9b2-a9be-4052-a448-ec5112025942-kyUTPL",IAMAuth="ENABLED",ClientPasswordAuthType="SQL_SERVER_AUTHENTICATION" \
    --role-arn "arn:aws:iam::1234567890:role/service-role/rds-proxy-role-1674792657645"\
    --vpc-subnet-ids "subnet-xxx" "subnet-yyy" \
    --vpc-security-group-ids sg-xxx
```
 3. Register your RDS DB with the proxy:

```
aws rds register-db-proxy-targets \
    --db-proxy-name sqlproxy \
    --db-instance-identifiers "sqlexpress"

```

 4. Ensure your IAM User/Role allows `rds-db:connect` as per [AWS IAM docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.IAMPolicy.html)
 5. Enter resulting Proxy FQDN below in server variable
 6. `go run test.go`

**Expected behavior**

I expect the following output (with my patch i get the correct output):

```
$ go run test.go
Connected!
Microsoft SQL Server 2019 (RTM-CU16-GDR) (KB5014353) - 15.0.4236.7 (X64) 
        May 29 2022 15:55:47 
        Copyright (C) 2019 Microsoft Corporation
        Express Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)
```

Instead I get this output (without my patch):

```
$ go run query.go
Connected!
2023/01/29 12:04:02 Error preparing SQL statement:federated authentication is not supported by the server
exit status 1
```

### Further technical details
SQL Server version: Any (SQL 2019 Express)
Operating system: Any (MacOS Ventura 13.1 M1)

**Additional context**

prelogin definitions are here:
https://github.com/microsoft/go-mssqldb/blob/main/tds.go#L104

.NET 6 works just fine with Microsoft.Data.SqlClient which implies to me its not an issue with the implementation of the protocol.
Working .NET code [here](https://gist.github.com/mattgillard/f63debb281c9eb26488ea788a5893090).

Debugger screenshot prior to readPrelogin response:

CleanShot 2023-01-31 at 11 27 22@2x

And after readPrelogin (no key for preloginFEDAUTHREQUIRED):

CleanShot 2023-01-31 at 11 30 01@2x

### PR DESCRIPTION
**Pull request by mattgillard**
This situation occurs with AWS RDS Proxy for MS SQL server as an example but may occur elsewhere.
The solution is to bypass the error message if we are not going through an ADAL workflow.

This resolves #84

### CODE REVIEW

**Comment by mattgillard** [comment]
@microsoft-github-policy-service agree

**Comment by shueybubbles** [comment]
thx for adding the example!

**Review by shueybubbles — APPROVED** [review]
:shipit:

**Comment by mattgillard** [comment]
i repushed with go.{mod|sum} files so hopefully it passes integration tests.

**Comment by shueybubbles** [comment]
I need to figure out why this test is unreliable. TestMessageQueueWithErrors

**Review by stuartpa — APPROVED** [review]

**Pull request merged**
